"use client"
import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import StyledComponentsRegistry from "./registry";
import { DefaultProviders } from "@/components/default-Provider";
import { BackToTop } from "@/components/back-to-top";
import { FreeShippingBar } from "@/components/free-shipping-bar";
import { CartDrawer } from "@/components/cart-drawer";

const saira = Saira({
  weight: ['300', '400', '500', '600'],
  subsets: ["latin"]
});

// export const metadata: Metadata = {
//   title: "CAPPUTEENO",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={saira.className}>
        <StyledComponentsRegistry>
        <DefaultProviders>

        <Header/>
        <FreeShippingBar />
        {children}
        <BackToTop />
        <CartDrawer />
        
        </DefaultProviders>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
